### ISSUE TITLE
This Example is not use of Weight share?

### ISSUE THREAD

**Issue by xieydd** [Crysple/NNI-NAS-Example#1]
I notice this example is nas not enas, and it doesn`t use weight share like [this](https://github.com/microsoft/nni/blob/master/docs/zh_CN/AdvancedNas.md). Am i right?

**Comment by xieydd** [comment]
And if i want run this example, the version of nni is required?

**Comment by Crysple** [comment]
Yes it is only for NAS not ENAS.
NNI version must be equal or higher than v0.8.

**Comment by xieydd** [comment]
Thx for your reply, i will close the issue.
